routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('dashboard', 'DashboardController@index');

Route::get('products', 'ProductsController@index')->middleware('auth');
Route::get('delete-product/{orderItem}', 'ProductsController@deleteItem')->middleware('auth');

Route::resource('orders','OrderController')->middleware('auth');
Route::get('order-product/{product}','OrderController@orderProduct')->middleware('auth');
Route::get('export-product/{order}','OrderController@exportPDF')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

resources/views/admin_template.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset("/bower_components/admin-lte/plugins/fontawesome-free/css/all.min.css") }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset("/bower_components/admin-lte/dist/css/adminlte.min.css") }}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">


    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Order List</h1>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <a href="{{route('orders.create')}}">New Order</a>
                                <table id="example1" class="table table-bordered table-striped">
                                    <tr>
                                        <th>Order ID</th>
                                        <th>Order Created At</th>
                                        <th>Customer</th>
                                        <th>View</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                    @foreach($orders as $order)
                                        <tr>
                                            <td>{{$order->id}}</td>
                                            <td>{{$order->created_at}}</td>
                                            <td><a href="{{route('orders.edit',$order->id)}}">Edit</a></td>
                                            <td><a href="{{route('orders.show',$order->id)}}">View</a></td>
                                            <td>
                                                <form action="{{route('orders.destroy',$order->id)}}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                        @endforeach
                                        </ul>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- /.col-md-12 -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
        <div class="p-3">
            <h5>Title</h5>
            <p>Sidebar content</p>
        </div>
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
    </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ asset("/bower_components/admin-lte/plugins/jquery/jquery.min.js")}}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset("/bower_components/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js")}}"></script>
<!-- AdminLTE App -->
<script src="{{ asset("/bower_components/admin-lte/dist/js/adminlte.min.js")}}"></script>

<!-- DataTables -->
<script src="{{ asset("/bower_components/admin-lte/plugins/datatables/jquery.dataTables.min.js")}}"></script>
<script src="{{ asset("/bower_components/admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js")}}"></script>
<script src="{{ asset("/bower_components/admin-lte/plugins/datatables-responsive/js/dataTables.responsive.min.js")}}"></script>
<script src="{{ asset("/bower_components/admin-lte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js")}}"></script>

<script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true,
            "autoWidth": false,
        });
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });
</script>
</body>
</html>

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        <button class="btn btn-sm btn-success">
                            Test
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/order_pdf_view.blade.php
<div class="col-12">
    <div class="card card-primary">
        <div class="card-body">

            @if (\Session::has('success'))
                <div class="alert alert-success">
                    {!! \Session::get('success') !!}
                </div>
            @endif

            <br>
            <br>
            <h3>Order Details</h3>
            <label>User Name : </label> {{$order->user->name}}<br>
            <label>User Email : </label> {{$order->user->email}}<br>
            <label>Order ID : </label> {{$order->id}}<br>
            <label>Order Created at : </label> {{$order->created_at}}<br><br><br>


            <h3>Order Items</h3>
            <table id="example2" class="table table-bordered table-striped" width="100%">
                <thead>
                <tr>
                    <td>Product</td>
                    <td>Variant</td>
                    <td>Quantity</td>
                    <td>&nbsp;</td>
                </tr>
                </thead>
                @foreach($order->OrderItems as $orderItem)
                    <tr>
                        <td>{{$orderItem->product->name}}</td>
                        <td>{{$orderItem->variant->name}}</td>
                        <td>{{$orderItem->qty}}</td>
                        <td>
                            <a href="{{ url('delete-product/' . $orderItem->id) }}" onclick="return confirm('Are you sure you want to delete this item?')"; class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i></a></td>
                    </tr>
                @endforeach
            </table>

            <a class="btn btn-sm btn-success" href="{{ url('export-product/' . $order->id) }}">Export PDF</a>
        </div>
    </div>
</div>

resources/views/orders_create.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset("/bower_components/admin-lte/plugins/fontawesome-free/css/all.min.css") }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset("/bower_components/admin-lte/dist/css/adminlte.min.css") }}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset("/bower_components/admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css")}}">
    <link rel="stylesheet" href="{{ asset("/bower_components/admin-lte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css")}}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.dataTables.min.css"/>

</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">


    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Create new order</h1>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card card-primary" >
                            <div class="card-header">
                                <h3 class="card-title">New order</h3>
                            </div>
                            <div class="card-body">
                                <a href="{{route('orders.index')}}">Back</a>

                                <form method="POST" action="{{route('orders.store')}}" >
                                    @method('POST')
                                    @csrf
                                    <div class="form-group">
                                        <label>Select User: </label>
                                        <select name="user_id" class="custom-select">
                                            @foreach($users as $user)
                                                <option value="{{$user->id}}">{{$user->name}} - {{$user->email}}</option>
                                            @endforeach
                                        </select>
                                    </div>


                                        <table class="table ">
                                            <tr>
                                                <td><label>Product Name</label></td>
                                                <td><label>Product Description</label></td>
                                            </tr>
                                            @foreach($products as $product)
                                                <tr>
                                                    <td><h3>{{$product->name}}</h3></td>
                                                    <td><h3>{{$product->description}}</h3></td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        @foreach($product->variants as $variant)
                                                            <tr>
                                                                <td>{{$variant->name}}</td>
                                                                <td><input type="number" min="0" style="width: 30px;" value="0" id="qty[{{$product->id}}][{{$variant->id}}]" name="qty[{{$product->id}}][{{$variant->id}}]"></td>
                                                            </tr>
                                                        @endforeach
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><button id="qty[{{$product->id}}][{{$variant->id}}]" onclick="placeOrder(this.id)" class="btn btn-block btn-primary" type="submit">Order - {{ $product->name }}</button></td>
                                                </tr>
                                                @endforeach

                                        </table>

                                </form>

                            </div>
                        </div>
                    </div>
                    <!-- /.col-md-12 -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
</div>
<!-- ./wrapper -->

<script>
    function placeOrder(id) {
        var productIdQTY = document.getElementById(id).value;

        alert(productIdQTY);
    }
</script>

resources/views/orders_view.blade.php
@extends('layouts.app')

@section('content')
    <div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">View Order</h3>

                        <div class="float-right">
                            <a href="{{ url('products') }}">Add Product</a>
                        </div>

                    </div>
                    <div class="card-body">

                        @if (\Session::has('success'))
                            <div class="alert alert-success">
                                    {!! \Session::get('success') !!}
                            </div>
                        @endif

                        <a href="{{route('orders.index')}}">Back</a>
                        <br>
                        <br>
                        <h3>Order Details</h3>
                        <label>User Name : </label> {{$order->user->name}}<br>
                        <label>User Email : </label> {{$order->user->email}}<br>
                        <label>Order ID : </label> {{$order->id}}<br>
                        <label>Order Created at : </label> {{$order->created_at}}<br><br><br>


                        <h3>Order Items</h3>
                        <table id="example2" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <td>Product</td>
                                <td>Variant</td>
                                <td>Quantity</td>
                                <td>&nbsp;</td>
                            </tr>
                            </thead>
                            @foreach($order->OrderItems as $orderItem)
                                <tr>
                                    <td>{{$orderItem->product->name}}</td>
                                    <td>{{$orderItem->variant->name}}</td>
                                    <td>{{$orderItem->qty}}</td>
                                    <td>
                                        <a href="{{ url('delete-product/' . $orderItem->id) }}" onclick="return confirm('Are you sure you want to delete this item?')"; class="btn btn-sm btn-danger">
                                            <i class="fa fa-trash"></i></a></td>
                                </tr>
                            @endforeach
                        </table>

                        <a class="btn btn-sm btn-success" href="{{ url('export-product/' . $order->id) }}">Export PDF</a>
                    </div>
                </div>
            </div>
            <!-- /.col-md-12 -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content -->
@endsection