routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('dashboard', 'DashboardController@index');

Route::get('products', 'ProductsController@index')->middleware('auth');
Route::get('delete-product/{orderItem}', 'ProductsController@deleteItem')->middleware('auth');

Route::resource('orders','OrderController')->middleware('auth');
Route::get('order-product/{product}','OrderController@orderProduct')->middleware('auth');
Route::get('export-product/{order}','OrderController@exportPDF')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $guarded = ['id'];
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function OrderItems()
    {
        return $this->hasMany(OrderItem::class);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\OrderItem;
use App\Product;
use App\User;
use App\Variant;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PDF;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('orders.index', ['orders' => Order::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('orders_create', ['users' => User::all(), 'products' => Product::with('variants')->get()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        //get users order
        $order = Order::where('user_id', Auth::User()->id)->first();

        if (!$order) {
            $order = new Order();
        }

        $order->user_id = Auth::user()->id;

        if ($order->save()) {
            $order_item = new OrderItem();
            $order_item->qty = $request->input('qty');
            $order_item->order_id = $order->id;
            $order_item->product_id = $request->input('productId');
            $order_item->variant_id = $request->input('variant');
            $order_item->save();
        }

        return redirect()->route('orders.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        return view('orders_view', [
            'order' => $order->load('orderItems')
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('orders.edit', [
            'order' => $order->load('orderItems'), 'users' => User::all(),
            'products' => Product::with('variants')->get()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $data = $request->validate([
            'user_id' => 'required',
        ]);

        $order->update(['user_id' => $data['user_id']]);

        return redirect()->route('orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $order->delete();

        return redirect()->route('orders.index');
    }

    private function saveOrderDetails(Order $order, $data)
    {
        foreach ($data['qty'] as $key => $val)
        {
            foreach ($val as $k => $v)
            {
                if($v > 0)
                {
                    $order_item = new OrderItem();
                    $order_item->qty = $v;
                    $order_item->order_id = $order->id;
                    $order_item->product_id = $key;
                    $order_item->variant_id = $k;
                    $order_item->save();
                }
            }
        }
    }

    /**
     * @param Product $product
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function orderProduct(Product $product)
    {
        return view('orders.order-product', [
            'product' => $product,
            'variant' => Variant::all()
            ]);
    }

    /**
     * @param Order $order
     * @return mixed
     */
    public function exportPDF(Order $order)
    {
        $order = $order->load('orderItems');
        $pdf = PDF::loadView('order_pdf_view', [
            'order' => $order->load('orderItems')
        ]);
        // download PDF file with download method

        return $pdf->download('pdf_file.pdf');
    }
}

resources/views/orders/edit.blade.php
@extends('layouts.app')

@section('content')
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Assign User</h3>
                        </div>
                        <div class="card-body">

                            <a href="{{route('orders.index')}}">Back</a>

                            <form method="POST" action="{{route('orders.update',$order->id)}}">
                                @method('PUT')
                                @csrf
                                <label>User:</label>
                                <select name="user_id" class="custom-select">
                                    @foreach($users as $user)
                                        <option
                                                @if($user->id == $order->user_id)
                                                selected
                                                @endif
                                                value="{{$user->id}}">{{$user->name}} - {{$user->email}}

                                        </option>
                                    @endforeach
                                </select>
                                <div>&nbsp;</div>
                                <button class="btn btn-primary" type="submit">Assign User</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.col-md-12 -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
@endsection

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('content')
    <link rel="stylesheet" href="{{ asset("/bower_components/admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css")}}">

    <!-- Main content -->
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Orders</h3>
                    </div>
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Order ID</th>
                                <th>Order Created At</th>
                                <th>Customer</th>
                                <th>Assign User</th>
                                <th>View</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            @foreach($orders as $order)
                                <tbody>
                                <tr>
                                    <td>{{$order->id}}</td>
                                    <td>{{$order->created_at}}</td>
                                    <td>{{$order->user->name}}</td>
                                    <td><a href="{{route('orders.edit',$order->id)}}">Assign</a></td>
                                    <td><a href="{{route('orders.show',$order->id)}}">View</a></td>
                                    <td>
                                        <form action="{{route('orders.destroy',$order->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-block btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                </tbody>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
            <!-- /.col-md-12 -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
    <!-- /.content -->


<!-- DataTables -->
<script src="{{ asset("/bower_components/admin-lte/plugins/datatables/jquery.dataTables.min.js")}}"></script>
<script src="{{ asset("/bower_components/admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js")}}"></script>
<script src="{{ asset("/bower_components/admin-lte/plugins/datatables-responsive/js/dataTables.responsive.min.js")}}"></script>
<script src="{{ asset("/bower_components/admin-lte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js")}}"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.4/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>

<script>
    $(function () {
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,

            "buttons": [
                'copy', 'csv', 'excel', 'pdf'
            ]
        });
    });
</script>
@endsection

resources/views/orders/order-product.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Order Product</div>

                    <div class="card-body">

                        <form method="POST" action="{{route('orders.store')}}">
                            @csrf
                        {{ $product->name }} - {{ $product->description }}



                            <div class="form-group">
                                <label for="qty">Qauntity</label>
                                <input type="number" name="qty" required class="form-control" placeholder="Enter quantity">
                            </div>

                            <select class="form-control" id="variant" name="variant">
                                @foreach($variant as $variant)
                                    <option value="{{ $variant->id }}">{{ $variant->name }}</option>
                                @endforeach
                            </select>

                            <input name="productId" value="{{ $product->id }}" type="hidden">

                            <button type="submit" class="btn btn-success my-1">
                                <i class="fa fa-save"></i> &nbsp; Save</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection